version: '3'
services:
  postgres:
    image: 'postgres:alpine'
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=matejowy@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pass

